<?php
return array (
  'almamed.su' => 
  array (
    3 => 
    array (
      'url' => 'novosti/*',
      'app' => 'blog',
      '_name' => 'Выставки',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'blog_url_type' => '2',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    4 => 
    array (
      'url' => 'company-news/*',
      'app' => 'blog',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'blog_url_type' => '3',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    1 => 
    array (
      'url' => 'i/*',
      'app' => 'site',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'locale' => 'ru_RU',
    ),
    2 => 
    array (
      'url' => '*',
      'app' => 'shop',
      '_name' => 'АльмаМед - поставки медицинского оборудования по всей России',
      'theme' => 'osnovnaja_new_header',
      'theme_mobile' => 'osnovnaja_new_header',
      'locale' => 'ru_RU',
      'title' => 'АльмаМед - поставки медицинского оборудования по всей России',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'url_type' => '1',
      'type_id' => '0',
      'currency' => 'RUB',
      'public_stocks' => '0',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
      'ssl' => '1',
    ),
  ),
  'dev.almamed.su' => 
  array (
    3 => 
    array (
      'url' => 'blog/*',
      'app' => 'blog',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'locale' => 'ru_RU',
      'blog_url_type' => '2',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    1 => 
    array (
      'url' => 'vystavki/*',
      'app' => 'blog',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'locale' => 'ru_RU',
      'blog_url_type' => '2',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    2 => 
    array (
      'url' => '*',
      'app' => 'shop',
      'theme' => 'profitbuy',
      'theme_mobile' => 'profitbuy',
      'locale' => 'ru_RU',
      'private' => '1',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'url_type' => '1',
      'type_id' => '0',
      'currency' => 'RUB',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
    ),
  ),
);
