<?php
return array (
  'yandexmarket' => true,
  'yoss' => true,
  'consignmentru' => true,
  'invoiceru' => true,
  'cartsreport' => true,
  'error301' => true,
  'wmimageincat' => true,
  'productbrands' => true,
  'seo' => true,
  'watermark' => true,
  'directedit' => true,
  'currencyrates' => true,
  'quickeditor' => true,
  'vendorlink' => true,
  'accordion' => true,
  'form' => true,
  'plugmein' => true,
  'xml' => '1',
  'productmanager' => true,
  'nbpopupform' => true,
  'carts' => true,
  'wait' => true,
  'cml1c' => true,
  'wholesale' => true,
  'castomfield' => '1',
);
